//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_CIS_186.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInf
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string DoB { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Misc { get; set; }
        public string PreCode { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Days { get; set; }
    }
}
